### ISSUE TITLE
Syntax issues

### ISSUE THREAD

**Issue by dhaneshsalla** [dynobo/PyctureStream#1]
HI,

This is a great Idea and I appreciate this project. 
I am trying to run this project in my system and I have followed your steps. But I am facing few syntax issues in stream_webcam_to_kafka.py script. 

[cloudera@quickstart client]$ python stream_webcam_to_kafka.py
  File "stream_webcam_to_kafka.py", line 26
    interval: int = 5,
            ^
SyntaxError: invalid syntax
[cloudera@quickstart client]$

Could you please check on this.

**Comment by dynobo** [comment]
Hi,

which Python version are you using? 

(The problem might be, that your version doesn't support type annotations yet. Those have been introduced somewhere above version 3.5)

**Comment by dhaneshsalla** [comment]
Hi, Yes I am using old version. I will update my python package and will let you know the status.

One more issue popup , this is mostly likely my system issue.

I am using Ubuntu 18.04 and am unable to open my webcam. I tired with cheese and gucview applications , but both are throwing error message "Device not found ".

I have tried couple of recommendations and workarounds, but nothing is working for me. Could you please assist on this webcam setup, Please

**Comment by dynobo** [comment]
Sorry, but if you can't get the webcam to work with cheese, you'll probably have an driver or connection issue behond the scope of my project. I suggest you ask for help on a Ubuntu specific channel like https://askubuntu.com/ .

I'm looking forward to hear, if the Python upgrade helped, so!
